### ISSUE TITLE
Exported external package typings file error with TypeScript 1.7

### ISSUE THREAD

**Issue by EddyLane** [VaclavObornik/di-ts#9]
After upgrading to 1.7 I'm getting the following error message when importing:

`...node_modules/di-ts/index.ts(2,1): error TS2654: Exported external package typings file cannot contain tripleslash references. Please contact the package author to update the package definition.`

I might be able to get time to look at this later today if nobody else picks it up.

Eddy

**Comment by hisplan** [comment]
Noticed the same issue with TypeScript v1.7.5

**Comment by VaclavObornik** [comment]
Hi, 

thanks for PR Eddy! I've merged it and published to npm, could you guys try if is the problem resolved? Thanks!

**Comment by eneunaber** [comment]
With your last commit you added 

```
+/// <reference path="./di.d.ts"/>
+/// <reference path="./node_modules/reflect-metadata/reflect-metadata.d.ts"/>
```

back into index.ts which breaks it for TypeScript 1.7.5

**Comment by lbialy** [comment]
Confirmed, broken 1.7.x since last commit.

**Comment by EddyLane** [comment]
Hi, Sorry I totally dropped off the face of the earth. @eneunaber is right, you should just need to revert your last commit @VaclavObornik. You need references to external definitions in your local definitions file to satisfy 1.7.x.   

Until this is resolved I have a fork which i'm currently using: https://github.com/EddyLane/di-ts that you all can use if you need it.
